name: Backup Mautic Workflow
on:
  workflow_dispatch:
    inputs:
      brand:
        description: 'Brand identifier (e.g., default, brandA). Defaults to "default".'
        default: 'default'
        required: false
    
jobs:
  backup:
    runs-on: ubuntu-latest
    environment:
      name: mautic-${{ github.event.inputs.brand || 'default' }}
    env:
      BRAND_NAME: ${{ github.event.inputs.brand || 'default' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Backup Mautic
        uses: ./.github/actions/run-remote-script
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ vars.LINODE_IP }}
          script: scripts/backup_mautic.sh
          env: "BRAND_NAME='${{ env.BRAND_NAME }}' DB_NAME='${{ vars.DB_NAME }}' MYSQL_ROOT_PASSWORD='${{ secrets.MYSQL_ROOT_PASSWORD }}'"
