name: Backup Mautic Workflow
on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Backup Mautic
        uses: ./.github/actions/run-remote-script
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ vars.LINODE_IP }}
          script: scripts/backup_mautic.sh
          env: "COMPOSE_PROJECT_NAME='${{ vars.COMPOSE_PROJECT_NAME }}' DEPLOY_DIR='${{ vars.DEPLOY_DIR }}' DB_NAME='${{ vars.DB_NAME }}' MYSQL_ROOT_PASSWORD='${{ secrets.MYSQL_ROOT_PASSWORD }}'"
